core/urls.py
from django import views
from django.urls import path, include
from core.views import *

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("products/<pid>/", product_detail_view, name="product-detail"),


    path("about_us/", about_us, name="about_us"),
    path("dashboard/", customer_dashboard, name="dashboard"),
    path("checkout/<oid>/", checkout, name="checkout"),
    path("payment-completed/", payment_completed_view, name="payment-completed"),
    path("payment-failed/", payment_failed_view, name="payment-failed"),
    path("dashboard/order/<id>/", order_detail, name="order-detail"),
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),

     # Homepage
    path("cart/", cart_view, name="cart"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),
    path("update-cart/", update_cart, name="update-cart"),
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax-add-review"),
    path("products/", product_list_view, name="product-list"),
    path("search/", search_view, name="search"),
    path("product/<pid>/", product_detail_view, name="product-detail"),
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name="vendor-detail"),
    path("search/", search_view, name="search"),
    
    #add review
    path("ajax-add-review/<pid>", ajax_add_review, name="ajax-add-review")
]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls", namespace="userauths")),
    path("useradmin/", include("useradmin.urls")),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),

]

userauths/models.py
from enum import unique
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from core.constants import ROLE_CHOICES

class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='customer')
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']
    def __str__(self):
        return self.username

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="image", null=True, blank=True)
    full_name = models.CharField(max_length=200, null=True, blank=True)
    bio = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True) 
    address = models.CharField(max_length=200, null=True, blank=True) 
    country = models.CharField(max_length=200, null=True, blank=True) 
    verified = models.BooleanField(default=False, null=True, blank=True)
    
    def __str__(self):
        return f"{self.user.username} - {self.full_name} - {self.bio}"

class ContactUs(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200) 
    subject = models.CharField(max_length=200) 
    message = models.TextField()

    class Meta:
        verbose_name = "Contact Us"
        verbose_name_plural = "Contact Us"

    def __str__(self):
        return self.full_name

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
 
post_save.connect(create_user_profile, sender=User)

post_save.connect(save_user_profile, sender=User)  

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
from userauths.models import User
from core.constants import ROLE_CHOICES


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": _("Username")}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": _("Email")}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": _("Password")}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": _("Confirm Password")}))
    role = forms.ChoiceField(choices=ROLE_CHOICES, widget=forms.Select())

    class Meta:
        model = User
        fields = ['username', 'email', 'role']

userauths/views.py
from django.shortcuts import redirect, render
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.utils.translation import gettext as _
from userauths.models import User


def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            role = form.cleaned_data.get("role")
            messages.success(
                request,
                _(f"Hello {username}, your account was created successfully.")
            )
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password=form.cleaned_data['password1']
            )
            if new_user:
                login(request, new_user)
                if role == "vendor":
                    return redirect("useradmin:dashboard")
                else:
                    return redirect("core:index")
    else:
        form = UserRegisterForm()
    return render(request, "userauths/sign-up.html", {"form": form})


def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, _("You are already logged in."))
        if request.user.role == "vendor":
            return redirect("useradmin:dashboard")
        else:
            return redirect("core:index")

    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        try:
            user_obj = User.objects.get(email=email)
            user = authenticate(request, email=user_obj.email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, _("Login successfully!"))
                if user.role == "vendor":
                    return redirect("useradmin:dashboard")
                else:
                    return redirect("core:index")
            else:
                messages.warning(request, _("User does not exist. Create an account."))
        except:
            messages.warning(request, f"User with {email} does not exists")

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, f"Login successfully!")
            if user.role == "vendor":
                return redirect("useradmin:dashboard")
            else:
                return redirect("core:index")
        else:
            messages.warning(request, "User does not exist. Create an account.")

    context = {}

    return render(request, "userauths/sign-in.html", context)

def logout_view(request):
    logout(request)
    messages.success(request, "You logged out.")
    return redirect("userauths:sign-in")
        
        

templates/userauths/sign-in.html
{% extends 'partials/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

<main class="main pages">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>{% trans "Home" %}</a>
                <span></span> {% trans "Pages" %} <span></span> {% trans "My Account" %}
            </div>
        </div>
    </div>
    <div class="page-content pt-150 pb-150">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                    <div class="row">
                        <div class="col-lg-6 pr-30 d-none d-lg-block">
                            <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.png' %}" alt="" />
                        </div>
                        <div class="col-lg-6 col-md-8">
                            <div class="login_wrap widget-taber-content background-white">
                                <div class="padding_eight_all bg-white">
                                    <div class="heading_s1">
                                        <h1 class="mb-5">{% trans "Login" %}</h1>
                                        <p class="mb-30">{% trans "Don't have an account?" %} <a href="{% url 'userauths:sign-up' %}">{% trans "Create here" %}</a></p>
                                    </div>
                                    <form method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" required name="email" placeholder="{% trans 'Username or Email *' %}" />
                                        </div>
                                        <div class="form-group">
                                            <input required type="password" name="password" placeholder="{% trans 'Your password *' %}" />
                                        </div>
                                        <div class="login_footer form-group mb-50">
                                            <div class="chek-form">
                                                <div class="custome-checkbox">
                                                    <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                                    <label class="form-check-label" for="exampleCheckbox1"><span>{% trans "Remember me" %}</span></label>
                                                </div>
                                            </div>
                                            <a class="text-muted" href="#">{% trans "Forgot password?" %}</a>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-heading btn-block hover-up" name="login">{% trans "Log in" %}</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

templates/userauths/sign-up.html
{% extends 'partials/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>{% trans "Home" %}</a>
                    <span></span> {% trans "Pages" %} <span></span> {% trans "My Account" %}
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">

                                        {% if form.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{form.errors}}</strong>
                                        </div>
                                        {% endif %}


                                        <div class="heading_s1">
                                            <h1 class="mb-5">{% trans "Create an Account" %}</h1>
                                            <p class="mb-30">{% trans "Already have an account?" %} <a href="{% url 'userauths:sign-in' %}">Login</a></p>
                                        </div>
                                        <form method="post" method="POST">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                {{form.username}}
                                            </div>
                                            <div class="form-group">
                                                {{form.email}}
                                            </div>
                                            <div class="form-group">
                                                {{form.password1}}
                                            </div>
                                            <div class="form-group">
                                                {{form.password2}}
                                            </div>
                                            <div class="form-group">
                                                <label for="id_role" class="font-weight-bold">{% trans "Account Type" %}</label>
                                                <select name="role" id="id_role" class="form-control">
                                                    <option value="customer">{% trans "Customer - I want to buy products" %}</option>
                                                    <option value="vendor">{% trans "Vendor - I want to sell products" %}</option>
                                                </select>
                                            </div>
                                            <div class="form-group mb-30">
                                                <button type="submit" class="btn btn-fill-out btn-block hover-up font-weight-bold" name="login">{% trans "Submit & Register" %}</button>
                                            </div>
                                            <p class="font-xs text-muted"><strong>{% trans "Note:" %}</strong>{% trans "Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our privacy policy" %}</p>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <div class="card-login mt-115">
                                    <a href="#" class="social-login facebook-login">
                                        <img src="{% static 'assets/imgs/theme/icons/logo-facebook.svg' %}" alt="" />
                                        <span>{% trans "Continue with Facebook" %}</span>
                                    </a>
                                    <a href="#" class="social-login google-login">
                                        <img src="{% static 'assets/imgs/theme/icons/logo-google.svg' %}" alt="" />
                                        <span>{% trans "Continue with Google" %}</span>
                                    </a>
                                    <a href="#" class="social-login apple-login">
                                        <img src="{% static 'assets/imgs/theme/icons/logo-apple.svg' %}" alt="" />
                                        <span>{% trans "Continue with Apple" %}</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}